
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-31T04:24:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "20909ae22a2933d0b5fe43bae6d900095c6c6a23",
 "version": "1.18.0.post0.dev113"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
