KEY_EVENT_UPLOAD = "upload"
KEY_EVENT_DOWNLOAD = "download"
KEY_EVENT_CREATE_README = "create-readme"
KEY_EVENT_UPDATE = "update"
KEY_EVENT_DELETE = "delete"
KEY_EVENT_CREATE = "create"
KEY_EVENT_ADD_EVENT = "add-event"
KEY_EVENT_SYNC = "sync"
KEY_EVENT_CREATE_API = "create-api"

# User Input message here
USER_SERVICE_NAME_INPUT_MSG = "Input service name for the event >> "
INPUT_MESSAGE_LIBS = "Input name of libraries for the event separated with ( , )\n>> "
INPUT_MESSAGE_AUTOMATIONS = "Input name of automations for the event separated with ( , )\n>> "
INPUT_MESSAGE_SERVICE = "Input name of angular service for the event\n>> "
INPUT_MESSAGE_PACKAGES_NAME = "Input name of packages for the event separated with ( , )\n>> "
INPUT_MESSAGE_STYLES = "Input list of css to be added in styles separated with ( , ). Leave bank if not required.\n>> "
INPUT_MESSAGE_SCRIPTS = "Input list of scripts to be added in scripts separated with ( , ). Leave bank if not required.\n>> "
INPUT_UPLOAD_FILEPATH = "Input filepath that is to be uploaded\n>> "
INPUT_UPLOAD_OUT_PATH = "Input output filepath, complete path where file is to be downloaded\n>> "

# ERROR_MSG
ERR_LIBS_SHOULD_BE_LIST = "key 'libs' should be a list of libraries in event"
ERR_SCRIPTS_SHOULD_BE_LIST = "key 'scripts' should be a list of libraries in event"
ERR_AUTOMATIONS_SHOULD_BE_LIST = "key 'automations' should be a list in event"
ERR_COMPONENT_NAMES_SHOULD_BE_LIST = "key 'component_names' should be a list in event"
ERR_PACKAGES_SHOULD_BE_LIST = "key 'packages' should be a list in event"
ERR_FILES_SHOULD_BE_LIST = "Files should be a list in event"

ERR_LIBRARY_NOT_PRESENT = "No Library present in the event"
ERR_SERVICE_NAME_NOT_PRESENT = "Missing Service Name"
ERR_AUTOMATIONS_NOT_PRESENT = "No Automation present in the event"
ERR_COMPONENT_NAMES_NOT_PRESENT = "Component names not present in event"
ERR_PACKAGES_NOT_PRESENT = "Packages not found"
ERR_FILES_NOT_PRESENT = "Missing key 'files' in download-files event"
ERR_SCRIPTS_OR_STYLES_MISSING = "Event does not have any styles or scripts"
ERR_SCRIPTS_MISSING = "Event does not have any scripts"
ERR_IMPORTS_OR_PROVIDER_MISSING = "Event does not have any imports or provider"

#KEYS here
KEY_COMPONENTS = "components"
KEY_COMPONENT_NAME = "component_name"
KEY_COMPONENT_PATH = "component_path"
KEY_COMPONENT_FILES = "component_files"
KEY_SERVICE_NAME = "service_name"
KEY_LIBS = "libs"
KEY_EVENT_TYPE = "event_type"
KEY_AUTOMATIONS = "automations"
KEY_PACKAGES = "packages"
KEY_FILES = "files"
KEY_FILE_LINK = "file_link"
KEY_OUT_PATH = "out_path"
KEY_FILE_PATH = "file_path"
KEY_STYLES = "styles"
KEY_SCRIPTS = "scripts"
KEY_IMPORTS = "imports"
KEY_PROVIDERS = "providers"
KEY_AUTH_GUARD_FILE_LINK = "auth_gaurd_file_link"
KEY_AUTH_GAURD_FILE_PATH = "auth_gaurd_file"
KEY_ROUTES_FILE_LINK = "routes_file_link"
KEY_URLS_PY_FILE_LINK = "urls_py_file_link"
KEY_SETTINGS_PY_FILE_LINK = "settings_py_file_link"
KEY_FIND_AND_REPLACE_EVENTS = "find_and_replace_events"
KEY_FIND_TEXT = "find_text"
KEY_REPLACE_TEXT = "replace_with"
KEY_MODULE_NAME = "module_name"
KEY_MODULE_PATH = "module_path"

# Declare constants
EVENT_CREATE_REACTJS_COMPONENT_CLASS = "create-reactjs-component-class"
EVENT_CREATE_ANGULAR_MODULE_ROUTING = "create-angular-module-routing"
EVENT_CREATE_NAVBAR_JSON = "create-navbar-json"
EVENT_CREATE_SIDEBAR_JSON = "create-sidebar-json"
EVENT_CREATE_MULTIPLE_ANGULAR_COMPONENTS = "create-multiple-angular-components"
EVENT_CREATE_ANGULAR_MODULE = "create-angular-module"
EVENT_INSTALL_PYTHON3_LIBRARIES = "install-python3-libraries"
EVENT_ADD_SCRIPT_TO_INDEX = "add-script-to-index"
EVENT_UPDATE_SETTINGS_PY = "update-settings-py"
EVENT_REPLACE_IN_FILE = "replace-in-file"
EVENT_UPDATE_URLS_PY = "update-urls-py"
EVENT_UPDATE_ANGULAR_ROUTES = "update-angular-routes"
EVENT_UPDATE_ANGULAR_MODULES = "update-angular-modules"
EVENT_UPDATE_ANGULAR_JSON = "update-angular-json"
EVENT_INSTALL_NPM_LIBRARIES = "install-npm-libraries"
EVENT_DOWNLOAD_FILES = "download-files"
EVENT_DJANGO_AUTOMATIONS = "django-automations"
EVENT_CREATE_PYTHON_PACKAGE = "create-python-package"
EVENT_CREATE_ANGULAR_SERVICE = "create-angular-service"
EVENT_CREATE_ANGULAR_COMPONENT = "create-angular-component"
EVENT_COPY_ANGULAR_COMPONENT = "copy-angular-component"
EVENT_ANGULAR_UI_LIB = "angular-ui-lib"
EVENT_ANGULAR_AUTOMATIONS = "angular-automations"
EVENT_ADD_NG_LIBRARY = "add-ng-library"

# Declare API Urls here
BASE_URL = "https://api.ask-jennie.com/"
TEXT_UPLOAD_API = BASE_URL + "v1/file_upload/"


KEY_STACK_ANGULAR_UI_LIB = "angular-ui-lib"
KEY_STACK_ANGULAR_AUTOMATION = "angular-automations"
KEY_STACK_DJANGO_AUTOMATIONS = "django-automations"




