
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-26T15:51:24-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "f269d49b6eb6c54171b00168787680c23eff5e30",
 "version": "2.7.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
