# Generated by Django 4.0.6 on 2023-01-18 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('informasaun', '0007_fileanunsiu_titulu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_order', models.CharField(max_length=150)),
                ('presu_ida', models.CharField(max_length=150)),
                ('presu_order', models.CharField(max_length=150)),
                ('status_hare', models.BooleanField(default=False, verbose_name='Staus hare')),
                ('status_resposta', models.BooleanField(default=False, verbose_name='Staus resposta')),
                ('data_order', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('hashed', models.TextField(blank=True, null=True)),
                ('produtu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informasaun.produtu')),
                ('user_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
