# Generated by Django 4.0.6 on 2023-01-18 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vizitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaorder',
            name='data_order',
        ),
        migrations.RemoveField(
            model_name='listaorder',
            name='status_hare',
        ),
        migrations.RemoveField(
            model_name='listaorder',
            name='status_resposta',
        ),
        migrations.RemoveField(
            model_name='listaorder',
            name='user_order',
        ),
    ]
