# Generated by Django 4.0.6 on 2023-01-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizitor', '0004_order_deskrisaun'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='resposta',
            field=models.TextField(blank=True, null=True, verbose_name='resposta'),
        ),
    ]
