# Generated by Django 4.0.6 on 2023-01-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizitor', '0003_order_listaorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deskrisaun',
            field=models.TextField(blank=True, null=True),
        ),
    ]
