
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-29T02:27:22+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b93810e8eec3d9efc7a07984f0d9febe6e398bc3",
 "version": "0.5.dev2305"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
