
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-26T01:26:56-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "8be8279f1d19ba278959a5ec96da82a53e465737",
 "version": "0.29.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
