
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-26T14:46:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c1a1dd8ad8bf3b452c123b713a6120f32cab48bf",
 "version": "0.9.89"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
