# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.business_recipient_address_object import BusinessRecipientAddressObject
from circle import configuration


class TestBusinessRecipientAddressObject(unittest.TestCase):
    """BusinessRecipientAddressObject unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
