# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.fiat_payment_polymorphic import FiatPaymentPolymorphic
from circle import configuration


class TestFiatPaymentPolymorphic(unittest.TestCase):
    """FiatPaymentPolymorphic unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
