# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.address_tag import AddressTag
from circle import configuration


class TestAddressTag(unittest.TestCase):
    """AddressTag unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
