# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.transfer_source_location import TransferSourceLocation
from circle import configuration


class TestTransferSourceLocation(unittest.TestCase):
    """TransferSourceLocation unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
