# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.detailed_refund import DetailedRefund
from circle import configuration


class TestDetailedRefund(unittest.TestCase):
    """DetailedRefund unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
