# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.fiat_payout import FiatPayout
from circle import configuration


class TestFiatPayout(unittest.TestCase):
    """FiatPayout unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
