# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.fiat_cancel import FiatCancel
from circle import configuration


class TestFiatCancel(unittest.TestCase):
    """FiatCancel unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
