# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.payment_intent import PaymentIntent
from circle import configuration


class TestPaymentIntent(unittest.TestCase):
    """PaymentIntent unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
