# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.expire_payment_intent_response import ExpirePaymentIntentResponse
from circle import configuration


class TestExpirePaymentIntentResponse(unittest.TestCase):
    """ExpirePaymentIntentResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
