# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.get_payout_response import GetPayoutResponse
from circle import configuration


class TestGetPayoutResponse(unittest.TestCase):
    """GetPayoutResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
