# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.card_update import CardUpdate
from circle import configuration


class TestCardUpdate(unittest.TestCase):
    """CardUpdate unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
