# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.stablecoin import Stablecoin
from circle import configuration


class TestStablecoin(unittest.TestCase):
    """Stablecoin unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
