# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.simple_billing_details import SimpleBillingDetails
from circle import configuration


class TestSimpleBillingDetails(unittest.TestCase):
    """SimpleBillingDetails unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
