# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.payment_info_payment_and_refund import PaymentInfoPaymentAndRefund
from circle import configuration


class TestPaymentInfoPaymentAndRefund(unittest.TestCase):
    """PaymentInfoPaymentAndRefund unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
