# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.metadata_phone_email import MetadataPhoneEmail
from circle import configuration


class TestMetadataPhoneEmail(unittest.TestCase):
    """MetadataPhoneEmail unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
