# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.channel_response import ChannelResponse
from circle import configuration


class TestChannelResponse(unittest.TestCase):
    """ChannelResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
