# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.list_business_sen_accounts_response import ListBusinessSenAccountsResponse
from circle import configuration


class TestListBusinessSenAccountsResponse(unittest.TestCase):
    """ListBusinessSenAccountsResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
