# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.mock_chargeback_creation_request import MockChargebackCreationRequest
from circle import configuration


class TestMockChargebackCreationRequest(unittest.TestCase):
    """MockChargebackCreationRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
