# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.detailed_payment import DetailedPayment
from circle import configuration


class TestDetailedPayment(unittest.TestCase):
    """DetailedPayment unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
