# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.get_address_book_recipient import GetAddressBookRecipient
from circle import configuration


class TestGetAddressBookRecipient(unittest.TestCase):
    """GetAddressBookRecipient unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
