# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.get_business_deposit_address_response import GetBusinessDepositAddressResponse
from circle import configuration


class TestGetBusinessDepositAddressResponse(unittest.TestCase):
    """GetBusinessDepositAddressResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
