# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.list_address_book_recipients_response import ListAddressBookRecipientsResponse
from circle import configuration


class TestListAddressBookRecipientsResponse(unittest.TestCase):
    """ListAddressBookRecipientsResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
