# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.create_card_response import CreateCardResponse
from circle import configuration


class TestCreateCardResponse(unittest.TestCase):
    """CreateCardResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
