# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.list_business_transfers_response import ListBusinessTransfersResponse
from circle import configuration


class TestListBusinessTransfersResponse(unittest.TestCase):
    """ListBusinessTransfersResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
