# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.get_business_sen_account_instructions_response import GetBusinessSenAccountInstructionsResponse
from circle import configuration


class TestGetBusinessSenAccountInstructionsResponse(unittest.TestCase):
    """GetBusinessSenAccountInstructionsResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
