# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.metadata_payout import MetadataPayout
from circle import configuration


class TestMetadataPayout(unittest.TestCase):
    """MetadataPayout unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
