# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.get_wallet_response import GetWalletResponse
from circle import configuration


class TestGetWalletResponse(unittest.TestCase):
    """GetWalletResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
