# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.bank_address_iban_supported import BankAddressIbanSupported
from circle import configuration


class TestBankAddressIbanSupported(unittest.TestCase):
    """BankAddressIbanSupported unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
