# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.list_business_balances_response import ListBusinessBalancesResponse
from circle import configuration


class TestListBusinessBalancesResponse(unittest.TestCase):
    """ListBusinessBalancesResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
