# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.mock_wire_payment_request import MockWirePaymentRequest
from circle import configuration


class TestMockWirePaymentRequest(unittest.TestCase):
    """MockWirePaymentRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
