# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.address_description import AddressDescription
from circle import configuration


class TestAddressDescription(unittest.TestCase):
    """AddressDescription unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
