# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.get_public_key_response import GetPublicKeyResponse
from circle import configuration


class TestGetPublicKeyResponse(unittest.TestCase):
    """GetPublicKeyResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
