# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.wire_instruction_beneficiary import WireInstructionBeneficiary
from circle import configuration


class TestWireInstructionBeneficiary(unittest.TestCase):
    """WireInstructionBeneficiary unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
