# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.id_settlement import IdSettlement
from circle import configuration


class TestIdSettlement(unittest.TestCase):
    """IdSettlement unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
