# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.get_business_transfer_response import GetBusinessTransferResponse
from circle import configuration


class TestGetBusinessTransferResponse(unittest.TestCase):
    """GetBusinessTransferResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
