# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.create_ach_account_response import CreateAchAccountResponse
from circle import configuration


class TestCreateAchAccountResponse(unittest.TestCase):
    """CreateAchAccountResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
