# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.wire_instruction import WireInstruction
from circle import configuration


class TestWireInstruction(unittest.TestCase):
    """WireInstruction unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
