# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.get_business_wire_account_response import GetBusinessWireAccountResponse
from circle import configuration


class TestGetBusinessWireAccountResponse(unittest.TestCase):
    """GetBusinessWireAccountResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
