# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.fiat_payout_creation_request import FiatPayoutCreationRequest
from circle import configuration


class TestFiatPayoutCreationRequest(unittest.TestCase):
    """FiatPayoutCreationRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
