# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.card_exp_month import CardExpMonth
from circle import configuration


class TestCardExpMonth(unittest.TestCase):
    """CardExpMonth unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
