# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.business_destination_request import BusinessDestinationRequest
from circle import configuration


class TestBusinessDestinationRequest(unittest.TestCase):
    """BusinessDestinationRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
