# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.list_channels_response import ListChannelsResponse
from circle import configuration


class TestListChannelsResponse(unittest.TestCase):
    """ListChannelsResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
