# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.payout_status import PayoutStatus
from circle import configuration


class TestPayoutStatus(unittest.TestCase):
    """PayoutStatus unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
