# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.sen_instruction import SenInstruction
from circle import configuration


class TestSenInstruction(unittest.TestCase):
    """SenInstruction unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
