# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.ach_creation_request import AchCreationRequest
from circle import configuration


class TestAchCreationRequest(unittest.TestCase):
    """AchCreationRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
