# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.identity_address import IdentityAddress
from circle import configuration


class TestIdentityAddress(unittest.TestCase):
    """IdentityAddress unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
