# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.basic_chargeback_history import BasicChargebackHistory
from circle import configuration


class TestBasicChargebackHistory(unittest.TestCase):
    """BasicChargebackHistory unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
