# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.identity import Identity
from circle import configuration


class TestIdentity(unittest.TestCase):
    """Identity unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
