# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.crypto_payout_destination_type import CryptoPayoutDestinationType
from circle import configuration


class TestCryptoPayoutDestinationType(unittest.TestCase):
    """CryptoPayoutDestinationType unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
