# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest

import circle
from circle.model.transfer_destination_location import TransferDestinationLocation
from circle import configuration


class TestTransferDestinationLocation(unittest.TestCase):
    """TransferDestinationLocation unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
