
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-31T13:00:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "77aedda2b3e870b3a638070d262e1512549fb9a5",
 "version": "1.18.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
