
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-31T13:07:41-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "99cda7442e055760ac6c5668f5e2699d2e33de28",
 "version": "v1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
