from .production_mykubectl_series_1 import production
from .production_mykubectl_series_2 import production_series_2

from .sandbox_mykubectl_series_1 import sanbox
from .sandbox_mykubectl_series_2 import sandbox_series_2