from pybulldozer.general.node import Node
class Structure:
    summarize:bool
    __nodelist:[Node]
    def __init__(self, summarize:bool=False):
        ...
    def __len__(self):
        ...
    def __contains__(self, node:Node):
        ...
    def get_node(self, targetNode:Node) -> Node:
        ...
    def node_in_structure(self, node:Node) -> bool:
        ...
    def add_node(self, newNode:Node) -> None:
        ...
    def get_node_list(self, sorted:bool=False, tagname_filter:str=None):
        ...
    def get_formatted_structure(self, indentation:int=1, show_attribs:bool=False, add_id:bool=False) -> str:
        ...
    def get_signature(self):
        ...
    def get_node_by_id(self, node_id:str):
        ...
