# Generated by Django 4.1.4 on 2023-01-21 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_alter_employee_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkingTimeRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_day",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Sunday"),
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thurstay"),
                            (5, "Friday"),
                            (6, "Saturday"),
                        ],
                        verbose_name="Week day",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Start time")),
                ("end_time", models.TimeField(verbose_name="End time")),
                (
                    "work_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to="employees.workschedule",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="WorkingHourRange",
        ),
    ]
