# Generated by Django 4.1.4 on 2023-01-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_workingtimerange_delete_workinghourrange"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workingtimerange",
            old_name="week_day",
            new_name="weekday",
        ),
    ]
