# Generated by Django 4.1.4 on 2023-01-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_rename_week_day_workingtimerange_weekday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workingtimerange",
            name="weekday",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (6, "Sunday"),
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thurstay"),
                    (4, "Friday"),
                    (5, "Saturday"),
                ],
                verbose_name="Week day",
            ),
        ),
    ]
