# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import circle
from circle.paths.v1_address_book_recipients_id import delete  # noqa: E501
from circle import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV1AddressBookRecipientsId(ApiTestMixin, unittest.TestCase):
    """
    V1AddressBookRecipientsId unit test stubs
        Delete an address book recipient  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = delete.ApiFordelete(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200
    response_body = ''


if __name__ == '__main__':
    unittest.main()
