
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-25T07:41:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9ff39962d0f06f7650d899debff6c45cfa95bf99",
 "version": "v23.02.00a230126"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
