
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: envoy.distribution.repo:package

from setuptools import setup

setup(**{
    'author': 'Ryan Northey',
    'author_email': 'ryan@synca.io',
    'description': '"Release publishing tool used in Envoy proxy\'s CI"',
    'entry_points': {
        'console_scripts': [
            'envoy.distribution.repo=envoy.distribution.repo:cmd',
        ],
    },
    'install_requires': (
        'abstracts>=0.0.12',
        'aio.core>=0.9.1',
        'aio.run.runner>=0.3.3',
        'envoy.base.utils>=0.3.9',
        'verboselogs',
    ),
    'license': 'Apache Software License 2.0',
    'long_description': """
envoy.distribution.repo
=======================

Repo publishing tool used in Envoy proxy's CI
""",
    'maintainer': 'Ryan Northey',
    'maintainer_email': 'ryan@synca.io',
    'name': 'envoy.distribution.repo',
    'namespace_packages': (
    ),
    'package_data': {
        'envoy.distribution.repo': (
            'py.typed',
        ),
    },
    'packages': (
        'envoy.distribution.repo',
    ),
    'url': 'https://github.com/envoyproxy/pytooling/tree/main/envoy.distribution.repo',
    'version': '0.0.8',
})
