# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notebooks/CLI_Version.ipynb.

# %% auto 0
__all__ = ['version', 'app']

# %% ../../notebooks/CLI_Version.ipynb 3
import typer

import airt
from ..client import _replace_env_var, _fix_cli_doc_string

# %% ../../notebooks/CLI_Version.ipynb 4
from airt.cli.version import version as _version

version = _version

version.__doc__ = _replace_env_var(version.__doc__)

# %% ../../notebooks/CLI_Version.ipynb 5
app = typer.Typer()
app.command()(version)
