# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arg_services/mining/v1/major_claim.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from arg_services.mining.v1 import adu_pb2 as arg__services_dot_mining_dot_v1_dot_adu__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(arg_services/mining/v1/major_claim.proto\x12\x16\x61rg_services.mining.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a arg_services/mining/v1/adu.proto\x1a\x1cgoogle/api/annotations.proto\"\xa9\x02\n\x11MajorClaimRequest\x12\x1a\n\x08language\x18\x01 \x01(\tR\x08language\x12S\n\x08segments\x18\x02 \x03(\x0b\x32\x37.arg_services.mining.v1.MajorClaimRequest.SegmentsEntryR\x08segments\x12\x14\n\x05limit\x18\x04 \x01(\x04R\x05limit\x12/\n\x06\x65xtras\x18\x0f \x01(\x0b\x32\x17.google.protobuf.StructR\x06\x65xtras\x1a\\\n\rSegmentsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x35\n\x05value\x18\x02 \x01(\x0b\x32\x1f.arg_services.mining.v1.SegmentR\x05value:\x02\x38\x01\"\x89\x01\n\x12MajorClaimResponse\x12\x42\n\x07ranking\x18\x01 \x03(\x0b\x32(.arg_services.mining.v1.MajorClaimResultR\x07ranking\x12/\n\x06\x65xtras\x18\x0f \x01(\x0b\x32\x17.google.protobuf.StructR\x06\x65xtras\"D\n\x10MajorClaimResult\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12 \n\x0bprobability\x18\x02 \x01(\x01R\x0bprobability2\x9c\x01\n\x11MajorClaimService\x12\x86\x01\n\nMajorClaim\x12).arg_services.mining.v1.MajorClaimRequest\x1a*.arg_services.mining.v1.MajorClaimResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/mining/v1/major_claimB\xa3\x01\n\x1a\x63om.arg_services.mining.v1B\x0fMajorClaimProtoP\x01\xa2\x02\x03\x41MX\xaa\x02\x15\x41rgServices.Mining.V1\xca\x02\x15\x41rgServices\\Mining\\V1\xe2\x02!ArgServices\\Mining\\V1\\GPBMetadata\xea\x02\x17\x41rgServices::Mining::V1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arg_services.mining.v1.major_claim_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.arg_services.mining.v1B\017MajorClaimProtoP\001\242\002\003AMX\252\002\025ArgServices.Mining.V1\312\002\025ArgServices\\Mining\\V1\342\002!ArgServices\\Mining\\V1\\GPBMetadata\352\002\027ArgServices::Mining::V1'
  _MAJORCLAIMREQUEST_SEGMENTSENTRY._options = None
  _MAJORCLAIMREQUEST_SEGMENTSENTRY._serialized_options = b'8\001'
  _MAJORCLAIMSERVICE.methods_by_name['MajorClaim']._options = None
  _MAJORCLAIMSERVICE.methods_by_name['MajorClaim']._serialized_options = b'\202\323\344\223\002\033:\001*\"\026/mining/v1/major_claim'
  _MAJORCLAIMREQUEST._serialized_start=163
  _MAJORCLAIMREQUEST._serialized_end=460
  _MAJORCLAIMREQUEST_SEGMENTSENTRY._serialized_start=368
  _MAJORCLAIMREQUEST_SEGMENTSENTRY._serialized_end=460
  _MAJORCLAIMRESPONSE._serialized_start=463
  _MAJORCLAIMRESPONSE._serialized_end=600
  _MAJORCLAIMRESULT._serialized_start=602
  _MAJORCLAIMRESULT._serialized_end=670
  _MAJORCLAIMSERVICE._serialized_start=673
  _MAJORCLAIMSERVICE._serialized_end=829
# @@protoc_insertion_point(module_scope)
