"""
    Splitit.OnBoarding.Api.V2

    Splitit's Onboarding API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import splitit_client
from splitit_client.model.country_response import CountryResponse
globals()['CountryResponse'] = CountryResponse
from splitit_client.model.countries_response import CountriesResponse


class TestCountriesResponse(unittest.TestCase):
    """CountriesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCountriesResponse(self):
        """Test CountriesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CountriesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
