"""
    Splitit.OnBoarding.Api.V2

    Splitit's Onboarding API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import splitit_client
from splitit_client.model.processor_authentication_parameters_request import ProcessorAuthenticationParametersRequest
globals()['ProcessorAuthenticationParametersRequest'] = ProcessorAuthenticationParametersRequest
from splitit_client.model.processor_response import ProcessorResponse


class TestProcessorResponse(unittest.TestCase):
    """ProcessorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProcessorResponse(self):
        """Test ProcessorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProcessorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
