"""
    Splitit.OnBoarding.Api.V2

    Splitit's Onboarding API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import splitit_client
from splitit_client.model.processor_response import ProcessorResponse
globals()['ProcessorResponse'] = ProcessorResponse
from splitit_client.model.processors_response import ProcessorsResponse


class TestProcessorsResponse(unittest.TestCase):
    """ProcessorsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProcessorsResponse(self):
        """Test ProcessorsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProcessorsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
