"""
    Splitit.OnBoarding.Api.V2

    Splitit's Onboarding API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import splitit_client
from splitit_client.model.country_response import CountryResponse


class TestCountryResponse(unittest.TestCase):
    """CountryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCountryResponse(self):
        """Test CountryResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CountryResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
