"""
    Splitit.OnBoarding.Api.V2

    Splitit's Onboarding API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import unittest

import os
from splitit_client.api_client import ApiClient
from splitit_client.api.data_api import DataApi  # noqa: E501
from splitit_client import Configuration


class TestDataApi(unittest.TestCase):
    """DataApi unit test stubs"""

    def setUp(self):
        client_id = os.environ["ONBOARDING_SPLITIT_CLIENT_ID"]
        client_secret = os.environ["ONBOARDING_SPLITIT_CLIENT_SECRET"]
        configuration = Configuration(client_id=client_id, client_secret=client_secret)
        api_client = ApiClient(configuration)
        self.api = DataApi(api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_get_countries(self):
        """Test case for get_countries

        """
        response = self.api.get_countries()
        assert response is not None, "Received null response"

if __name__ == '__main__':
    unittest.main()
