# Generated by Django 4.1.4 on 2023-01-08 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                parent_link=True,
                primary_key=True,
                related_name="patient",
                serialize=False,
                to="core.person",
            ),
        ),
    ]
