# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_guide',
                'doc_host': 'https://ayushmandloi2.github.io',
                'git_url': 'https://github.com/ayushmandloi2/nbdev_guide',
                'lib_path': 'nbdev_guide'},
  'syms': { 'nbdev_guide.core': { 'nbdev_guide.core.HelloSayer': ('core.html#hellosayer', 'nbdev_guide/core.py'),
                                  'nbdev_guide.core.HelloSayer.__init__': ('core.html#hellosayer.__init__', 'nbdev_guide/core.py'),
                                  'nbdev_guide.core.HelloSayer.say': ('core.html#hellosayer.say', 'nbdev_guide/core.py'),
                                  'nbdev_guide.core.foo': ('core.html#foo', 'nbdev_guide/core.py'),
                                  'nbdev_guide.core.say_hello': ('core.html#say_hello', 'nbdev_guide/core.py')}}}
