# Generated by Django 4.0.6 on 2022-10-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informasaun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konteuduprodutu',
            name='data_produsaun',
            field=models.DateField(verbose_name='Data Publika'),
        ),
        migrations.AlterField(
            model_name='produtu',
            name='data',
            field=models.DateField(verbose_name='Data Publika'),
        ),
    ]
