# Generated by Django 4.0.6 on 2023-01-17 06:53

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jeral', '0001_initial'),
        ('informasaun', '0002_alter_konteuduprodutu_data_produsaun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anunsiu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_main', models.ImageField(blank=True, default='pajina/default.png', null=True, upload_to='anunsiu/')),
                ('status', models.BooleanField(default=False, verbose_name='Staus Publika')),
                ('data', models.DateField(verbose_name='Data')),
                ('date_created', models.DateField(blank=True, null=True, verbose_name='Data Rejistu')),
                ('hashed', models.TextField(blank=True, null=True)),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Hili User')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenAnunsiu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='pajina/default.png', upload_to='anunsiu/')),
                ('date_created', models.DateField(blank=True, null=True, verbose_name='Data Rejistu')),
                ('hashed', models.TextField(blank=True, null=True)),
                ('anunsiu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anunsiu', to='informasaun.anunsiu')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Hili User')),
            ],
        ),
        migrations.CreateModel(
            name='KonteuduImagenAnunsiu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskrisaun', ckeditor.fields.RichTextField(max_length=70)),
                ('date_created', models.DateField(blank=True, null=True, verbose_name='Data Rejistu')),
                ('hashed', models.TextField(blank=True, null=True)),
                ('imagenanunsiu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenanunsiu', to='informasaun.imagenanunsiu')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Hili User')),
            ],
        ),
        migrations.CreateModel(
            name='KonteuduAnunsiu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulu', models.CharField(max_length=250)),
                ('konteudu', ckeditor.fields.RichTextField()),
                ('status', models.BooleanField(default=False, verbose_name='Staus Publika')),
                ('data', models.DateField(verbose_name='Data')),
                ('date_created', models.DateField(blank=True, null=True, verbose_name='Data Rejistu')),
                ('hashed', models.TextField(blank=True, null=True)),
                ('anunsiu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informasaun.anunsiu', verbose_name='Hili informasaun')),
                ('lingua', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jeral.lingua')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Hili User')),
            ],
        ),
    ]
