# Generated by Django 4.0.6 on 2023-01-17 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('informasaun', '0003_anunsiu_imagenanunsiu_konteuduimagenanunsiu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriaInformasaun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulu', models.CharField(max_length=250)),
                ('data', models.DateField(verbose_name='Data')),
                ('date_created', models.DateField(blank=True, null=True, verbose_name='Data Rejistu')),
                ('hashed', models.TextField(blank=True, null=True)),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Hili User')),
            ],
        ),
        migrations.AddField(
            model_name='informasaun',
            name='kategoriainformasaun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informasaun.kategoriainformasaun', verbose_name='Hili Kategoria info'),
        ),
    ]
