# Generated by Django 4.0.6 on 2023-01-17 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('informasaun', '0005_fileanunsiu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileanunsiu',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Hili User'),
        ),
    ]
