# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yggdrasil_decision_forests/learner/hyperparameters_optimizer/optimizers/random.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yggdrasil_decision_forests.learner.hyperparameters_optimizer import hyperparameters_optimizer_pb2 as yggdrasil__decision__forests_dot_learner_dot_hyperparameters__optimizer_dot_hyperparameters__optimizer__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='yggdrasil_decision_forests/learner/hyperparameters_optimizer/optimizers/random.proto',
  package='yggdrasil_decision_forests.model.hyperparameters_optimizer_v2.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\nTyggdrasil_decision_forests/learner/hyperparameters_optimizer/optimizers/random.proto\x12\x43yggdrasil_decision_forests.model.hyperparameters_optimizer_v2.proto\x1a\\yggdrasil_decision_forests/learner/hyperparameters_optimizer/hyperparameters_optimizer.proto\"0\n\x15RandomOptimizerConfig\x12\x17\n\nnum_trials\x18\x01 \x01(\x03:\x03\x31\x30\x30:\xbb\x01\n\x06random\x12N.yggdrasil_decision_forests.model.hyperparameters_optimizer_v2.proto.Optimizer\x18\xe8\x07 \x01(\x0b\x32Z.yggdrasil_decision_forests.model.hyperparameters_optimizer_v2.proto.RandomOptimizerConfig')
  ,
  dependencies=[yggdrasil__decision__forests_dot_learner_dot_hyperparameters__optimizer_dot_hyperparameters__optimizer__pb2.DESCRIPTOR,])


RANDOM_FIELD_NUMBER = 1000
random = _descriptor.FieldDescriptor(
  name='random', full_name='yggdrasil_decision_forests.model.hyperparameters_optimizer_v2.proto.random', index=0,
  number=1000, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)


_RANDOMOPTIMIZERCONFIG = _descriptor.Descriptor(
  name='RandomOptimizerConfig',
  full_name='yggdrasil_decision_forests.model.hyperparameters_optimizer_v2.proto.RandomOptimizerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_trials', full_name='yggdrasil_decision_forests.model.hyperparameters_optimizer_v2.proto.RandomOptimizerConfig.num_trials', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=299,
)

DESCRIPTOR.message_types_by_name['RandomOptimizerConfig'] = _RANDOMOPTIMIZERCONFIG
DESCRIPTOR.extensions_by_name['random'] = random
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RandomOptimizerConfig = _reflection.GeneratedProtocolMessageType('RandomOptimizerConfig', (_message.Message,), {
  'DESCRIPTOR' : _RANDOMOPTIMIZERCONFIG,
  '__module__' : 'yggdrasil_decision_forests.learner.hyperparameters_optimizer.optimizers.random_pb2'
  # @@protoc_insertion_point(class_scope:yggdrasil_decision_forests.model.hyperparameters_optimizer_v2.proto.RandomOptimizerConfig)
  })
_sym_db.RegisterMessage(RandomOptimizerConfig)

random.message_type = _RANDOMOPTIMIZERCONFIG
yggdrasil__decision__forests_dot_learner_dot_hyperparameters__optimizer_dot_hyperparameters__optimizer__pb2.Optimizer.RegisterExtension(random)

# @@protoc_insertion_point(module_scope)
