
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-26T22:50:48+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "bfa86884f74a81227662e3e04cd84a5ab122a4c1",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
