# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import public_registry_pb2 as public__registry__pb2


class StaticStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Security = channel.unary_unary(
                '/public_registry.Static/Security',
                request_serializer=public__registry__pb2.SecurityRequest.SerializeToString,
                response_deserializer=public__registry__pb2.SecurityResponse.FromString,
                )
        self.Securities = channel.unary_unary(
                '/public_registry.Static/Securities',
                request_serializer=public__registry__pb2.SecuritiesRequest.SerializeToString,
                response_deserializer=public__registry__pb2.SecuritiesResponse.FromString,
                )
        self.Assets = channel.unary_unary(
                '/public_registry.Static/Assets',
                request_serializer=public__registry__pb2.AssetsRequest.SerializeToString,
                response_deserializer=public__registry__pb2.AssetsResponse.FromString,
                )
        self.Protocols = channel.unary_unary(
                '/public_registry.Static/Protocols',
                request_serializer=public__registry__pb2.ProtocolsRequest.SerializeToString,
                response_deserializer=public__registry__pb2.ProtocolsResponse.FromString,
                )
        self.Chains = channel.unary_unary(
                '/public_registry.Static/Chains',
                request_serializer=public__registry__pb2.ChainsRequest.SerializeToString,
                response_deserializer=public__registry__pb2.ChainsResponse.FromString,
                )
        self.ProtocolAssets = channel.unary_unary(
                '/public_registry.Static/ProtocolAssets',
                request_serializer=public__registry__pb2.ProtocolAssetsRequest.SerializeToString,
                response_deserializer=public__registry__pb2.ProtocolAssetsResponse.FromString,
                )
        self.MarketableProtocolAssets = channel.unary_unary(
                '/public_registry.Static/MarketableProtocolAssets',
                request_serializer=public__registry__pb2.MarketableProtocolAssetsRequest.SerializeToString,
                response_deserializer=public__registry__pb2.MarketableProtocolAssetsResponse.FromString,
                )
        self.AuthChallenge = channel.unary_unary(
                '/public_registry.Static/AuthChallenge',
                request_serializer=public__registry__pb2.AuthChallengeRequest.SerializeToString,
                response_deserializer=public__registry__pb2.AuthChallengeResponse.FromString,
                )
        self.Auth = channel.unary_unary(
                '/public_registry.Static/Auth',
                request_serializer=public__registry__pb2.AuthRequest.SerializeToString,
                response_deserializer=public__registry__pb2.AuthResponse.FromString,
                )


class StaticServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Security(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Securities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Assets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Protocols(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chains(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProtocolAssets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarketableProtocolAssets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthChallenge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Auth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StaticServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Security': grpc.unary_unary_rpc_method_handler(
                    servicer.Security,
                    request_deserializer=public__registry__pb2.SecurityRequest.FromString,
                    response_serializer=public__registry__pb2.SecurityResponse.SerializeToString,
            ),
            'Securities': grpc.unary_unary_rpc_method_handler(
                    servicer.Securities,
                    request_deserializer=public__registry__pb2.SecuritiesRequest.FromString,
                    response_serializer=public__registry__pb2.SecuritiesResponse.SerializeToString,
            ),
            'Assets': grpc.unary_unary_rpc_method_handler(
                    servicer.Assets,
                    request_deserializer=public__registry__pb2.AssetsRequest.FromString,
                    response_serializer=public__registry__pb2.AssetsResponse.SerializeToString,
            ),
            'Protocols': grpc.unary_unary_rpc_method_handler(
                    servicer.Protocols,
                    request_deserializer=public__registry__pb2.ProtocolsRequest.FromString,
                    response_serializer=public__registry__pb2.ProtocolsResponse.SerializeToString,
            ),
            'Chains': grpc.unary_unary_rpc_method_handler(
                    servicer.Chains,
                    request_deserializer=public__registry__pb2.ChainsRequest.FromString,
                    response_serializer=public__registry__pb2.ChainsResponse.SerializeToString,
            ),
            'ProtocolAssets': grpc.unary_unary_rpc_method_handler(
                    servicer.ProtocolAssets,
                    request_deserializer=public__registry__pb2.ProtocolAssetsRequest.FromString,
                    response_serializer=public__registry__pb2.ProtocolAssetsResponse.SerializeToString,
            ),
            'MarketableProtocolAssets': grpc.unary_unary_rpc_method_handler(
                    servicer.MarketableProtocolAssets,
                    request_deserializer=public__registry__pb2.MarketableProtocolAssetsRequest.FromString,
                    response_serializer=public__registry__pb2.MarketableProtocolAssetsResponse.SerializeToString,
            ),
            'AuthChallenge': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthChallenge,
                    request_deserializer=public__registry__pb2.AuthChallengeRequest.FromString,
                    response_serializer=public__registry__pb2.AuthChallengeResponse.SerializeToString,
            ),
            'Auth': grpc.unary_unary_rpc_method_handler(
                    servicer.Auth,
                    request_deserializer=public__registry__pb2.AuthRequest.FromString,
                    response_serializer=public__registry__pb2.AuthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'public_registry.Static', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Static(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Security(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Static/Security',
            public__registry__pb2.SecurityRequest.SerializeToString,
            public__registry__pb2.SecurityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Securities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Static/Securities',
            public__registry__pb2.SecuritiesRequest.SerializeToString,
            public__registry__pb2.SecuritiesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Assets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Static/Assets',
            public__registry__pb2.AssetsRequest.SerializeToString,
            public__registry__pb2.AssetsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Protocols(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Static/Protocols',
            public__registry__pb2.ProtocolsRequest.SerializeToString,
            public__registry__pb2.ProtocolsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Chains(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Static/Chains',
            public__registry__pb2.ChainsRequest.SerializeToString,
            public__registry__pb2.ChainsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProtocolAssets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Static/ProtocolAssets',
            public__registry__pb2.ProtocolAssetsRequest.SerializeToString,
            public__registry__pb2.ProtocolAssetsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MarketableProtocolAssets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Static/MarketableProtocolAssets',
            public__registry__pb2.MarketableProtocolAssetsRequest.SerializeToString,
            public__registry__pb2.MarketableProtocolAssetsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AuthChallenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Static/AuthChallenge',
            public__registry__pb2.AuthChallengeRequest.SerializeToString,
            public__registry__pb2.AuthChallengeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Auth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Static/Auth',
            public__registry__pb2.AuthRequest.SerializeToString,
            public__registry__pb2.AuthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class CustomersStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/public_registry.Customers/Register',
                request_serializer=public__registry__pb2.RegisterRequest.SerializeToString,
                response_deserializer=public__registry__pb2.RegisterResponse.FromString,
                )
        self.Login = channel.unary_unary(
                '/public_registry.Customers/Login',
                request_serializer=public__registry__pb2.LoginRequest.SerializeToString,
                response_deserializer=public__registry__pb2.LoginResponse.FromString,
                )
        self.EmailConfirm = channel.unary_unary(
                '/public_registry.Customers/EmailConfirm',
                request_serializer=public__registry__pb2.EmailConfirmRequest.SerializeToString,
                response_deserializer=public__registry__pb2.EmailConfirmResponse.FromString,
                )
        self.PasswordUpdate = channel.unary_unary(
                '/public_registry.Customers/PasswordUpdate',
                request_serializer=public__registry__pb2.PasswordUpdateRequest.SerializeToString,
                response_deserializer=public__registry__pb2.PasswordUpdateResponse.FromString,
                )
        self.PasswordReset = channel.unary_unary(
                '/public_registry.Customers/PasswordReset',
                request_serializer=public__registry__pb2.PasswordResetRequest.SerializeToString,
                response_deserializer=public__registry__pb2.PasswordResetResponse.FromString,
                )
        self.Unsubscribe = channel.unary_unary(
                '/public_registry.Customers/Unsubscribe',
                request_serializer=public__registry__pb2.UnsubscribeRequest.SerializeToString,
                response_deserializer=public__registry__pb2.UnsubscribeResponse.FromString,
                )
        self.EmailUpdate = channel.unary_unary(
                '/public_registry.Customers/EmailUpdate',
                request_serializer=public__registry__pb2.EmailUpdateRequest.SerializeToString,
                response_deserializer=public__registry__pb2.EmailUpdateResponse.FromString,
                )
        self.CustomerInfo = channel.unary_unary(
                '/public_registry.Customers/CustomerInfo',
                request_serializer=public__registry__pb2.CustomerInfoRequest.SerializeToString,
                response_deserializer=public__registry__pb2.CustomerInfoResponse.FromString,
                )
        self.CustomerDetailsUpdate = channel.unary_unary(
                '/public_registry.Customers/CustomerDetailsUpdate',
                request_serializer=public__registry__pb2.CustomerDetailsUpdateRequest.SerializeToString,
                response_deserializer=public__registry__pb2.CustomerDetailsUpdateResponse.FromString,
                )
        self.PaymentMethodUpdate = channel.unary_unary(
                '/public_registry.Customers/PaymentMethodUpdate',
                request_serializer=public__registry__pb2.PaymentMethodUpdateRequest.SerializeToString,
                response_deserializer=public__registry__pb2.PaymentMethodUpdateResponse.FromString,
                )
        self.Licenses = channel.unary_unary(
                '/public_registry.Customers/Licenses',
                request_serializer=public__registry__pb2.LicensesRequest.SerializeToString,
                response_deserializer=public__registry__pb2.LicensesResponse.FromString,
                )
        self.LicenseUsage = channel.unary_unary(
                '/public_registry.Customers/LicenseUsage',
                request_serializer=public__registry__pb2.LicenseUsageRequest.SerializeToString,
                response_deserializer=public__registry__pb2.LicenseUsageResponse.FromString,
                )
        self.AddTerminal = channel.unary_unary(
                '/public_registry.Customers/AddTerminal',
                request_serializer=public__registry__pb2.AddTerminalRequest.SerializeToString,
                response_deserializer=public__registry__pb2.AddTerminalResponse.FromString,
                )
        self.RenewTerminal = channel.unary_unary(
                '/public_registry.Customers/RenewTerminal',
                request_serializer=public__registry__pb2.RenewTerminalRequest.SerializeToString,
                response_deserializer=public__registry__pb2.RenewTerminalResponse.FromString,
                )
        self.LicenseUpdate = channel.unary_unary(
                '/public_registry.Customers/LicenseUpdate',
                request_serializer=public__registry__pb2.LicenseUpdateRequest.SerializeToString,
                response_deserializer=public__registry__pb2.License.FromString,
                )
        self.AddBucketCredentials = channel.unary_unary(
                '/public_registry.Customers/AddBucketCredentials',
                request_serializer=public__registry__pb2.AddBucketCredentialsRequest.SerializeToString,
                response_deserializer=public__registry__pb2.AddBucketCredentialsResponse.FromString,
                )
        self.APICredentials = channel.unary_unary(
                '/public_registry.Customers/APICredentials',
                request_serializer=public__registry__pb2.APICredentialsRequest.SerializeToString,
                response_deserializer=public__registry__pb2.APICredentialsResponse.FromString,
                )
        self.AddAPICredentials = channel.unary_unary(
                '/public_registry.Customers/AddAPICredentials',
                request_serializer=public__registry__pb2.AddAPICredentialsRequest.SerializeToString,
                response_deserializer=public__registry__pb2.AddAPICredentialsResponse.FromString,
                )
        self.LoadTerminal = channel.unary_unary(
                '/public_registry.Customers/LoadTerminal',
                request_serializer=public__registry__pb2.LoadTerminalRequest.SerializeToString,
                response_deserializer=public__registry__pb2.LoadTerminalResponse.FromString,
                )
        self.SaveTerminal = channel.unary_unary(
                '/public_registry.Customers/SaveTerminal',
                request_serializer=public__registry__pb2.SaveTerminalRequest.SerializeToString,
                response_deserializer=public__registry__pb2.SaveTerminalResponse.FromString,
                )
        self.Certificate = channel.unary_unary(
                '/public_registry.Customers/Certificate',
                request_serializer=public__registry__pb2.CertificateRequest.SerializeToString,
                response_deserializer=public__registry__pb2.CertificateResponse.FromString,
                )
        self.Invoices = channel.unary_unary(
                '/public_registry.Customers/Invoices',
                request_serializer=public__registry__pb2.InvoicesRequest.SerializeToString,
                response_deserializer=public__registry__pb2.InvoicesResponse.FromString,
                )
        self.DownloadLauncher = channel.unary_stream(
                '/public_registry.Customers/DownloadLauncher',
                request_serializer=public__registry__pb2.DownloadLauncherRequest.SerializeToString,
                response_deserializer=public__registry__pb2.DownloadChunk.FromString,
                )
        self.DownloadInvoice = channel.unary_unary(
                '/public_registry.Customers/DownloadInvoice',
                request_serializer=public__registry__pb2.DownloadInvoiceRequest.SerializeToString,
                response_deserializer=public__registry__pb2.DownloadInvoiceResponse.FromString,
                )


class CustomersServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmailConfirm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PasswordUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PasswordReset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unsubscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmailUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CustomerInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CustomerDetailsUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PaymentMethodUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Licenses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LicenseUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTerminal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewTerminal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LicenseUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBucketCredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def APICredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddAPICredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadTerminal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveTerminal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Certificate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Invoices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadLauncher(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadInvoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=public__registry__pb2.RegisterRequest.FromString,
                    response_serializer=public__registry__pb2.RegisterResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=public__registry__pb2.LoginRequest.FromString,
                    response_serializer=public__registry__pb2.LoginResponse.SerializeToString,
            ),
            'EmailConfirm': grpc.unary_unary_rpc_method_handler(
                    servicer.EmailConfirm,
                    request_deserializer=public__registry__pb2.EmailConfirmRequest.FromString,
                    response_serializer=public__registry__pb2.EmailConfirmResponse.SerializeToString,
            ),
            'PasswordUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PasswordUpdate,
                    request_deserializer=public__registry__pb2.PasswordUpdateRequest.FromString,
                    response_serializer=public__registry__pb2.PasswordUpdateResponse.SerializeToString,
            ),
            'PasswordReset': grpc.unary_unary_rpc_method_handler(
                    servicer.PasswordReset,
                    request_deserializer=public__registry__pb2.PasswordResetRequest.FromString,
                    response_serializer=public__registry__pb2.PasswordResetResponse.SerializeToString,
            ),
            'Unsubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Unsubscribe,
                    request_deserializer=public__registry__pb2.UnsubscribeRequest.FromString,
                    response_serializer=public__registry__pb2.UnsubscribeResponse.SerializeToString,
            ),
            'EmailUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.EmailUpdate,
                    request_deserializer=public__registry__pb2.EmailUpdateRequest.FromString,
                    response_serializer=public__registry__pb2.EmailUpdateResponse.SerializeToString,
            ),
            'CustomerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.CustomerInfo,
                    request_deserializer=public__registry__pb2.CustomerInfoRequest.FromString,
                    response_serializer=public__registry__pb2.CustomerInfoResponse.SerializeToString,
            ),
            'CustomerDetailsUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.CustomerDetailsUpdate,
                    request_deserializer=public__registry__pb2.CustomerDetailsUpdateRequest.FromString,
                    response_serializer=public__registry__pb2.CustomerDetailsUpdateResponse.SerializeToString,
            ),
            'PaymentMethodUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PaymentMethodUpdate,
                    request_deserializer=public__registry__pb2.PaymentMethodUpdateRequest.FromString,
                    response_serializer=public__registry__pb2.PaymentMethodUpdateResponse.SerializeToString,
            ),
            'Licenses': grpc.unary_unary_rpc_method_handler(
                    servicer.Licenses,
                    request_deserializer=public__registry__pb2.LicensesRequest.FromString,
                    response_serializer=public__registry__pb2.LicensesResponse.SerializeToString,
            ),
            'LicenseUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.LicenseUsage,
                    request_deserializer=public__registry__pb2.LicenseUsageRequest.FromString,
                    response_serializer=public__registry__pb2.LicenseUsageResponse.SerializeToString,
            ),
            'AddTerminal': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTerminal,
                    request_deserializer=public__registry__pb2.AddTerminalRequest.FromString,
                    response_serializer=public__registry__pb2.AddTerminalResponse.SerializeToString,
            ),
            'RenewTerminal': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewTerminal,
                    request_deserializer=public__registry__pb2.RenewTerminalRequest.FromString,
                    response_serializer=public__registry__pb2.RenewTerminalResponse.SerializeToString,
            ),
            'LicenseUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.LicenseUpdate,
                    request_deserializer=public__registry__pb2.LicenseUpdateRequest.FromString,
                    response_serializer=public__registry__pb2.License.SerializeToString,
            ),
            'AddBucketCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBucketCredentials,
                    request_deserializer=public__registry__pb2.AddBucketCredentialsRequest.FromString,
                    response_serializer=public__registry__pb2.AddBucketCredentialsResponse.SerializeToString,
            ),
            'APICredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.APICredentials,
                    request_deserializer=public__registry__pb2.APICredentialsRequest.FromString,
                    response_serializer=public__registry__pb2.APICredentialsResponse.SerializeToString,
            ),
            'AddAPICredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAPICredentials,
                    request_deserializer=public__registry__pb2.AddAPICredentialsRequest.FromString,
                    response_serializer=public__registry__pb2.AddAPICredentialsResponse.SerializeToString,
            ),
            'LoadTerminal': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadTerminal,
                    request_deserializer=public__registry__pb2.LoadTerminalRequest.FromString,
                    response_serializer=public__registry__pb2.LoadTerminalResponse.SerializeToString,
            ),
            'SaveTerminal': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveTerminal,
                    request_deserializer=public__registry__pb2.SaveTerminalRequest.FromString,
                    response_serializer=public__registry__pb2.SaveTerminalResponse.SerializeToString,
            ),
            'Certificate': grpc.unary_unary_rpc_method_handler(
                    servicer.Certificate,
                    request_deserializer=public__registry__pb2.CertificateRequest.FromString,
                    response_serializer=public__registry__pb2.CertificateResponse.SerializeToString,
            ),
            'Invoices': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoices,
                    request_deserializer=public__registry__pb2.InvoicesRequest.FromString,
                    response_serializer=public__registry__pb2.InvoicesResponse.SerializeToString,
            ),
            'DownloadLauncher': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadLauncher,
                    request_deserializer=public__registry__pb2.DownloadLauncherRequest.FromString,
                    response_serializer=public__registry__pb2.DownloadChunk.SerializeToString,
            ),
            'DownloadInvoice': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadInvoice,
                    request_deserializer=public__registry__pb2.DownloadInvoiceRequest.FromString,
                    response_serializer=public__registry__pb2.DownloadInvoiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'public_registry.Customers', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Customers(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/Register',
            public__registry__pb2.RegisterRequest.SerializeToString,
            public__registry__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/Login',
            public__registry__pb2.LoginRequest.SerializeToString,
            public__registry__pb2.LoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EmailConfirm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/EmailConfirm',
            public__registry__pb2.EmailConfirmRequest.SerializeToString,
            public__registry__pb2.EmailConfirmResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PasswordUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/PasswordUpdate',
            public__registry__pb2.PasswordUpdateRequest.SerializeToString,
            public__registry__pb2.PasswordUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PasswordReset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/PasswordReset',
            public__registry__pb2.PasswordResetRequest.SerializeToString,
            public__registry__pb2.PasswordResetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Unsubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/Unsubscribe',
            public__registry__pb2.UnsubscribeRequest.SerializeToString,
            public__registry__pb2.UnsubscribeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EmailUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/EmailUpdate',
            public__registry__pb2.EmailUpdateRequest.SerializeToString,
            public__registry__pb2.EmailUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CustomerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/CustomerInfo',
            public__registry__pb2.CustomerInfoRequest.SerializeToString,
            public__registry__pb2.CustomerInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CustomerDetailsUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/CustomerDetailsUpdate',
            public__registry__pb2.CustomerDetailsUpdateRequest.SerializeToString,
            public__registry__pb2.CustomerDetailsUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PaymentMethodUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/PaymentMethodUpdate',
            public__registry__pb2.PaymentMethodUpdateRequest.SerializeToString,
            public__registry__pb2.PaymentMethodUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Licenses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/Licenses',
            public__registry__pb2.LicensesRequest.SerializeToString,
            public__registry__pb2.LicensesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LicenseUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/LicenseUsage',
            public__registry__pb2.LicenseUsageRequest.SerializeToString,
            public__registry__pb2.LicenseUsageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddTerminal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/AddTerminal',
            public__registry__pb2.AddTerminalRequest.SerializeToString,
            public__registry__pb2.AddTerminalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RenewTerminal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/RenewTerminal',
            public__registry__pb2.RenewTerminalRequest.SerializeToString,
            public__registry__pb2.RenewTerminalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LicenseUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/LicenseUpdate',
            public__registry__pb2.LicenseUpdateRequest.SerializeToString,
            public__registry__pb2.License.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddBucketCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/AddBucketCredentials',
            public__registry__pb2.AddBucketCredentialsRequest.SerializeToString,
            public__registry__pb2.AddBucketCredentialsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def APICredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/APICredentials',
            public__registry__pb2.APICredentialsRequest.SerializeToString,
            public__registry__pb2.APICredentialsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddAPICredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/AddAPICredentials',
            public__registry__pb2.AddAPICredentialsRequest.SerializeToString,
            public__registry__pb2.AddAPICredentialsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoadTerminal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/LoadTerminal',
            public__registry__pb2.LoadTerminalRequest.SerializeToString,
            public__registry__pb2.LoadTerminalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveTerminal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/SaveTerminal',
            public__registry__pb2.SaveTerminalRequest.SerializeToString,
            public__registry__pb2.SaveTerminalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Certificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/Certificate',
            public__registry__pb2.CertificateRequest.SerializeToString,
            public__registry__pb2.CertificateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Invoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/Invoices',
            public__registry__pb2.InvoicesRequest.SerializeToString,
            public__registry__pb2.InvoicesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadLauncher(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/public_registry.Customers/DownloadLauncher',
            public__registry__pb2.DownloadLauncherRequest.SerializeToString,
            public__registry__pb2.DownloadChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadInvoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.Customers/DownloadInvoice',
            public__registry__pb2.DownloadInvoiceRequest.SerializeToString,
            public__registry__pb2.DownloadInvoiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class AlphaBotStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChallengeInfo = channel.unary_unary(
                '/public_registry.AlphaBot/ChallengeInfo',
                request_serializer=public__registry__pb2.ChallengeInfoRequest.SerializeToString,
                response_deserializer=public__registry__pb2.ChallengeInfoResponse.FromString,
                )
        self.LinkWallet = channel.unary_unary(
                '/public_registry.AlphaBot/LinkWallet',
                request_serializer=public__registry__pb2.LinkWalletRequest.SerializeToString,
                response_deserializer=public__registry__pb2.LinkWalletResponse.FromString,
                )
        self.EnablePlugin = channel.unary_unary(
                '/public_registry.AlphaBot/EnablePlugin',
                request_serializer=public__registry__pb2.EnablePluginRequest.SerializeToString,
                response_deserializer=public__registry__pb2.EnablePluginResponse.FromString,
                )
        self.DisablePlugin = channel.unary_unary(
                '/public_registry.AlphaBot/DisablePlugin',
                request_serializer=public__registry__pb2.DisablePluginRequest.SerializeToString,
                response_deserializer=public__registry__pb2.DisablePluginResponse.FromString,
                )


class AlphaBotServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChallengeInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LinkWallet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnablePlugin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisablePlugin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlphaBotServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChallengeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.ChallengeInfo,
                    request_deserializer=public__registry__pb2.ChallengeInfoRequest.FromString,
                    response_serializer=public__registry__pb2.ChallengeInfoResponse.SerializeToString,
            ),
            'LinkWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.LinkWallet,
                    request_deserializer=public__registry__pb2.LinkWalletRequest.FromString,
                    response_serializer=public__registry__pb2.LinkWalletResponse.SerializeToString,
            ),
            'EnablePlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.EnablePlugin,
                    request_deserializer=public__registry__pb2.EnablePluginRequest.FromString,
                    response_serializer=public__registry__pb2.EnablePluginResponse.SerializeToString,
            ),
            'DisablePlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.DisablePlugin,
                    request_deserializer=public__registry__pb2.DisablePluginRequest.FromString,
                    response_serializer=public__registry__pb2.DisablePluginResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'public_registry.AlphaBot', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AlphaBot(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChallengeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.AlphaBot/ChallengeInfo',
            public__registry__pb2.ChallengeInfoRequest.SerializeToString,
            public__registry__pb2.ChallengeInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LinkWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.AlphaBot/LinkWallet',
            public__registry__pb2.LinkWalletRequest.SerializeToString,
            public__registry__pb2.LinkWalletResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnablePlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.AlphaBot/EnablePlugin',
            public__registry__pb2.EnablePluginRequest.SerializeToString,
            public__registry__pb2.EnablePluginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisablePlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public_registry.AlphaBot/DisablePlugin',
            public__registry__pb2.DisablePluginRequest.SerializeToString,
            public__registry__pb2.DisablePluginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
