import pysftp
from .aliases import PathLike as PathLike
from .auth import LikeSSHAuth as LikeSSHAuth, SSHAuth as SSHAuth
from _typeshed import Incomplete
from paramiko.hostkeys import HostKeyEntry as HostKeyEntry, HostKeys
from typing import BinaryIO

class PortHostKeys(HostKeys):
    port: Incomplete
    def __init__(self, filename: PathLike, port: int) -> None: ...

class Connection(pysftp.Connection):
    def __init__(self, authinfo: LikeSSHAuth) -> None: ...

def sftp_open(client: pysftp.Connection, remotepath: PathLike, mode: str = ...): ...
def sftp_download(client: pysftp.Connection, remotepath: PathLike, localpath: PathLike) -> None: ...
def sftp_download_bytes(client: pysftp.Connection, remotepath: PathLike) -> BinaryIO: ...
def sftp_upload_bytes(client: pysftp.Connection, data: BinaryIO, remotepath: PathLike, mode: str = ...) -> None: ...
