
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-27T10:46:53+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "bc4de205ab55053889526fb1a72b84979138f050",
 "version": "0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
