VERSION_YEAR = 2023
VERSION_MONTH = int('01')
VERSION_DAY = int('28')
VERSION_HOUR = int('08')
VERSION_MINUTE = int('00')
MAJOR_VERSION = 1
MINOR_VERSION = 11
PATCH_VERSION = 202301280800
version_date = '2023/01/28 08:00'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
