# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_helper_api/events.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_helper_api import common_pb2 as grpc__helper__api_dot_common__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1cgrpc_helper_api/events.proto\x1a\x1cgrpc_helper_api/common.proto",\n\rEventProperty\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t"9\n\x05\x45vent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12"\n\nproperties\x18\x02 \x03(\x0b\x32\x0e.EventProperty"K\n\x0b\x45ventStatus\x12\x12\n\x01r\x18\x01 \x01(\x0b\x32\x07.Result\x12\x15\n\x05\x65vent\x18\x02 \x01(\x0b\x32\x06.Event\x12\x11\n\tclient_id\x18\x03 \x01(\r"/\n\x0b\x45ventFilter\x12\r\n\x05names\x18\x01 \x03(\t\x12\x11\n\tclient_id\x18\x02 \x01(\r"#\n\x0e\x45ventInterrupt\x12\x11\n\tclient_id\x18\x01 \x01(\r":\n\x10\x45ventQueueStatus\x12\x12\n\x01r\x18\x01 \x01(\x0b\x32\x07.Result\x12\x12\n\nclient_ids\x18\x02 \x03(\r*X\n\x0f\x45ventApiVersion\x12\x15\n\x11\x45VENT_API_UNKNOWN\x10\x00\x12\x17\n\x13\x45VENT_API_SUPPORTED\x10\x01\x12\x15\n\x11\x45VENT_API_CURRENT\x10\x02\x32\xa8\x01\n\x0c\x45ventService\x12&\n\x06listen\x12\x0c.EventFilter\x1a\x0c.EventStatus0\x01\x12+\n\tinterrupt\x12\x0f.EventInterrupt\x1a\r.ResultStatus\x12\x1d\n\x04send\x12\x06.Event\x1a\r.ResultStatus\x12$\n\x07inspect\x12\x06.Empty\x1a\x11.EventQueueStatusB\x13\n\x0fgrpc_helper_apiP\x01\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "grpc_helper_api.events_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n\017grpc_helper_apiP\001"
    _EVENTAPIVERSION._serialized_start = 390
    _EVENTAPIVERSION._serialized_end = 478
    _EVENTPROPERTY._serialized_start = 62
    _EVENTPROPERTY._serialized_end = 106
    _EVENT._serialized_start = 108
    _EVENT._serialized_end = 165
    _EVENTSTATUS._serialized_start = 167
    _EVENTSTATUS._serialized_end = 242
    _EVENTFILTER._serialized_start = 244
    _EVENTFILTER._serialized_end = 291
    _EVENTINTERRUPT._serialized_start = 293
    _EVENTINTERRUPT._serialized_end = 328
    _EVENTQUEUESTATUS._serialized_start = 330
    _EVENTQUEUESTATUS._serialized_end = 388
    _EVENTSERVICE._serialized_start = 481
    _EVENTSERVICE._serialized_end = 649
# @@protoc_insertion_point(module_scope)
