
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-29T23:53:40+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "abe20d657ac6aab0bb64d5b4d04e39859d4ad461",
 "version": "0.13.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
