
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-26T10:14:47-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "67a12a04a1502974239dd76134ac03e3c41c8353",
 "version": "0.15.45"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
