
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-25T14:38:12-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "6368a49e8cdcfaa89de8ce6c7ae0af03486ae819",
 "version": "0.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
