# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reverb/cc/patterns.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tensorflow.core.protobuf import struct_pb2 as tensorflow_dot_core_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='reverb/cc/patterns.proto',
  package='deepmind.reverb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18reverb/cc/patterns.proto\x12\x0f\x64\x65\x65pmind.reverb\x1a%tensorflow/core/protobuf/struct.proto\"\x8a\x01\n\x0bPatternNode\x12\x19\n\x11\x66lat_source_index\x18\x01 \x01(\x05\x12\x0f\n\x05start\x18\x02 \x01(\x05H\x00\x12\x0e\n\x04stop\x18\x03 \x01(\x05H\x01\x12\x0e\n\x04step\x18\x04 \x01(\x05H\x02\x42\x0f\n\rstart_or_noneB\x0e\n\x0cstop_or_noneB\x0e\n\x0cstep_or_none\"\xa8\x02\n\tCondition\x12\x14\n\nstep_index\x18\x01 \x01(\x08H\x00\x12\x1d\n\x13steps_since_applied\x18\x02 \x01(\x08H\x00\x12\x17\n\rbuffer_length\x18\x03 \x01(\x08H\x00\x12\x18\n\x0eis_end_episode\x18\x04 \x01(\x08H\x00\x12\x1b\n\x11\x66lat_source_index\x18\t \x01(\x05H\x00\x12\x0c\n\x02\x65q\x18\x05 \x01(\x05H\x01\x12\x0c\n\x02ge\x18\x06 \x01(\x05H\x01\x12\x35\n\x06mod_eq\x18\x07 \x01(\x0b\x32#.deepmind.reverb.Condition.ModuloEqH\x01\x12\x0f\n\x07inverse\x18\x08 \x01(\x08\x1a#\n\x08ModuloEq\x12\x0b\n\x03mod\x18\x01 \x01(\x05\x12\n\n\x02\x65q\x18\x02 \x01(\x05\x42\x06\n\x04leftB\x05\n\x03\x63mp\"\xfd\x01\n\x08Priority\x12\x43\n\x0b\x63onstant_fn\x18\x01 \x01(\x0b\x32,.deepmind.reverb.Priority.ConstantPriorityFnH\x00\x12\x35\n\x08td_error\x18\x02 \x01(\x0b\x32!.deepmind.reverb.Priority.TDErrorH\x00\x1a#\n\x12\x43onstantPriorityFn\x12\r\n\x05value\x18\x01 \x01(\x01\x1a\x41\n\x07TDError\x12\x1b\n\x13max_priority_weight\x18\x01 \x01(\x01\x12\x19\n\x11\x66lat_source_index\x18\x02 \x01(\x05\x42\r\n\x0bpriority_fn\"\xe8\x01\n\x16StructuredWriterConfig\x12*\n\x04\x66lat\x18\x01 \x03(\x0b\x32\x1c.deepmind.reverb.PatternNode\x12\x36\n\x11pattern_structure\x18\x02 \x01(\x0b\x32\x1b.tensorflow.StructuredValue\x12\r\n\x05table\x18\x03 \x01(\t\x12+\n\x08priority\x18\x04 \x01(\x0b\x32\x19.deepmind.reverb.Priority\x12.\n\nconditions\x18\x05 \x03(\x0b\x32\x1a.deepmind.reverb.Conditionb\x06proto3')
  ,
  dependencies=[tensorflow_dot_core_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_PATTERNNODE = _descriptor.Descriptor(
  name='PatternNode',
  full_name='deepmind.reverb.PatternNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flat_source_index', full_name='deepmind.reverb.PatternNode.flat_source_index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='deepmind.reverb.PatternNode.start', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stop', full_name='deepmind.reverb.PatternNode.stop', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step', full_name='deepmind.reverb.PatternNode.step', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='start_or_none', full_name='deepmind.reverb.PatternNode.start_or_none',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='stop_or_none', full_name='deepmind.reverb.PatternNode.stop_or_none',
      index=1, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='step_or_none', full_name='deepmind.reverb.PatternNode.step_or_none',
      index=2, containing_type=None, fields=[]),
  ],
  serialized_start=85,
  serialized_end=223,
)


_CONDITION_MODULOEQ = _descriptor.Descriptor(
  name='ModuloEq',
  full_name='deepmind.reverb.Condition.ModuloEq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mod', full_name='deepmind.reverb.Condition.ModuloEq.mod', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eq', full_name='deepmind.reverb.Condition.ModuloEq.eq', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=507,
)

_CONDITION = _descriptor.Descriptor(
  name='Condition',
  full_name='deepmind.reverb.Condition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='step_index', full_name='deepmind.reverb.Condition.step_index', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steps_since_applied', full_name='deepmind.reverb.Condition.steps_since_applied', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buffer_length', full_name='deepmind.reverb.Condition.buffer_length', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_end_episode', full_name='deepmind.reverb.Condition.is_end_episode', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flat_source_index', full_name='deepmind.reverb.Condition.flat_source_index', index=4,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eq', full_name='deepmind.reverb.Condition.eq', index=5,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ge', full_name='deepmind.reverb.Condition.ge', index=6,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mod_eq', full_name='deepmind.reverb.Condition.mod_eq', index=7,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inverse', full_name='deepmind.reverb.Condition.inverse', index=8,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CONDITION_MODULOEQ, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='left', full_name='deepmind.reverb.Condition.left',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='cmp', full_name='deepmind.reverb.Condition.cmp',
      index=1, containing_type=None, fields=[]),
  ],
  serialized_start=226,
  serialized_end=522,
)


_PRIORITY_CONSTANTPRIORITYFN = _descriptor.Descriptor(
  name='ConstantPriorityFn',
  full_name='deepmind.reverb.Priority.ConstantPriorityFn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='deepmind.reverb.Priority.ConstantPriorityFn.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=661,
  serialized_end=696,
)

_PRIORITY_TDERROR = _descriptor.Descriptor(
  name='TDError',
  full_name='deepmind.reverb.Priority.TDError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_priority_weight', full_name='deepmind.reverb.Priority.TDError.max_priority_weight', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flat_source_index', full_name='deepmind.reverb.Priority.TDError.flat_source_index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=698,
  serialized_end=763,
)

_PRIORITY = _descriptor.Descriptor(
  name='Priority',
  full_name='deepmind.reverb.Priority',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='constant_fn', full_name='deepmind.reverb.Priority.constant_fn', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='td_error', full_name='deepmind.reverb.Priority.td_error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PRIORITY_CONSTANTPRIORITYFN, _PRIORITY_TDERROR, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='priority_fn', full_name='deepmind.reverb.Priority.priority_fn',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=525,
  serialized_end=778,
)


_STRUCTUREDWRITERCONFIG = _descriptor.Descriptor(
  name='StructuredWriterConfig',
  full_name='deepmind.reverb.StructuredWriterConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flat', full_name='deepmind.reverb.StructuredWriterConfig.flat', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pattern_structure', full_name='deepmind.reverb.StructuredWriterConfig.pattern_structure', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='table', full_name='deepmind.reverb.StructuredWriterConfig.table', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='priority', full_name='deepmind.reverb.StructuredWriterConfig.priority', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conditions', full_name='deepmind.reverb.StructuredWriterConfig.conditions', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=781,
  serialized_end=1013,
)

_PATTERNNODE.oneofs_by_name['start_or_none'].fields.append(
  _PATTERNNODE.fields_by_name['start'])
_PATTERNNODE.fields_by_name['start'].containing_oneof = _PATTERNNODE.oneofs_by_name['start_or_none']
_PATTERNNODE.oneofs_by_name['stop_or_none'].fields.append(
  _PATTERNNODE.fields_by_name['stop'])
_PATTERNNODE.fields_by_name['stop'].containing_oneof = _PATTERNNODE.oneofs_by_name['stop_or_none']
_PATTERNNODE.oneofs_by_name['step_or_none'].fields.append(
  _PATTERNNODE.fields_by_name['step'])
_PATTERNNODE.fields_by_name['step'].containing_oneof = _PATTERNNODE.oneofs_by_name['step_or_none']
_CONDITION_MODULOEQ.containing_type = _CONDITION
_CONDITION.fields_by_name['mod_eq'].message_type = _CONDITION_MODULOEQ
_CONDITION.oneofs_by_name['left'].fields.append(
  _CONDITION.fields_by_name['step_index'])
_CONDITION.fields_by_name['step_index'].containing_oneof = _CONDITION.oneofs_by_name['left']
_CONDITION.oneofs_by_name['left'].fields.append(
  _CONDITION.fields_by_name['steps_since_applied'])
_CONDITION.fields_by_name['steps_since_applied'].containing_oneof = _CONDITION.oneofs_by_name['left']
_CONDITION.oneofs_by_name['left'].fields.append(
  _CONDITION.fields_by_name['buffer_length'])
_CONDITION.fields_by_name['buffer_length'].containing_oneof = _CONDITION.oneofs_by_name['left']
_CONDITION.oneofs_by_name['left'].fields.append(
  _CONDITION.fields_by_name['is_end_episode'])
_CONDITION.fields_by_name['is_end_episode'].containing_oneof = _CONDITION.oneofs_by_name['left']
_CONDITION.oneofs_by_name['left'].fields.append(
  _CONDITION.fields_by_name['flat_source_index'])
_CONDITION.fields_by_name['flat_source_index'].containing_oneof = _CONDITION.oneofs_by_name['left']
_CONDITION.oneofs_by_name['cmp'].fields.append(
  _CONDITION.fields_by_name['eq'])
_CONDITION.fields_by_name['eq'].containing_oneof = _CONDITION.oneofs_by_name['cmp']
_CONDITION.oneofs_by_name['cmp'].fields.append(
  _CONDITION.fields_by_name['ge'])
_CONDITION.fields_by_name['ge'].containing_oneof = _CONDITION.oneofs_by_name['cmp']
_CONDITION.oneofs_by_name['cmp'].fields.append(
  _CONDITION.fields_by_name['mod_eq'])
_CONDITION.fields_by_name['mod_eq'].containing_oneof = _CONDITION.oneofs_by_name['cmp']
_PRIORITY_CONSTANTPRIORITYFN.containing_type = _PRIORITY
_PRIORITY_TDERROR.containing_type = _PRIORITY
_PRIORITY.fields_by_name['constant_fn'].message_type = _PRIORITY_CONSTANTPRIORITYFN
_PRIORITY.fields_by_name['td_error'].message_type = _PRIORITY_TDERROR
_PRIORITY.oneofs_by_name['priority_fn'].fields.append(
  _PRIORITY.fields_by_name['constant_fn'])
_PRIORITY.fields_by_name['constant_fn'].containing_oneof = _PRIORITY.oneofs_by_name['priority_fn']
_PRIORITY.oneofs_by_name['priority_fn'].fields.append(
  _PRIORITY.fields_by_name['td_error'])
_PRIORITY.fields_by_name['td_error'].containing_oneof = _PRIORITY.oneofs_by_name['priority_fn']
_STRUCTUREDWRITERCONFIG.fields_by_name['flat'].message_type = _PATTERNNODE
_STRUCTUREDWRITERCONFIG.fields_by_name['pattern_structure'].message_type = tensorflow_dot_core_dot_protobuf_dot_struct__pb2._STRUCTUREDVALUE
_STRUCTUREDWRITERCONFIG.fields_by_name['priority'].message_type = _PRIORITY
_STRUCTUREDWRITERCONFIG.fields_by_name['conditions'].message_type = _CONDITION
DESCRIPTOR.message_types_by_name['PatternNode'] = _PATTERNNODE
DESCRIPTOR.message_types_by_name['Condition'] = _CONDITION
DESCRIPTOR.message_types_by_name['Priority'] = _PRIORITY
DESCRIPTOR.message_types_by_name['StructuredWriterConfig'] = _STRUCTUREDWRITERCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PatternNode = _reflection.GeneratedProtocolMessageType('PatternNode', (_message.Message,), {
  'DESCRIPTOR' : _PATTERNNODE,
  '__module__' : 'reverb.cc.patterns_pb2'
  # @@protoc_insertion_point(class_scope:deepmind.reverb.PatternNode)
  })
_sym_db.RegisterMessage(PatternNode)

Condition = _reflection.GeneratedProtocolMessageType('Condition', (_message.Message,), {

  'ModuloEq' : _reflection.GeneratedProtocolMessageType('ModuloEq', (_message.Message,), {
    'DESCRIPTOR' : _CONDITION_MODULOEQ,
    '__module__' : 'reverb.cc.patterns_pb2'
    # @@protoc_insertion_point(class_scope:deepmind.reverb.Condition.ModuloEq)
    })
  ,
  'DESCRIPTOR' : _CONDITION,
  '__module__' : 'reverb.cc.patterns_pb2'
  # @@protoc_insertion_point(class_scope:deepmind.reverb.Condition)
  })
_sym_db.RegisterMessage(Condition)
_sym_db.RegisterMessage(Condition.ModuloEq)

Priority = _reflection.GeneratedProtocolMessageType('Priority', (_message.Message,), {

  'ConstantPriorityFn' : _reflection.GeneratedProtocolMessageType('ConstantPriorityFn', (_message.Message,), {
    'DESCRIPTOR' : _PRIORITY_CONSTANTPRIORITYFN,
    '__module__' : 'reverb.cc.patterns_pb2'
    # @@protoc_insertion_point(class_scope:deepmind.reverb.Priority.ConstantPriorityFn)
    })
  ,

  'TDError' : _reflection.GeneratedProtocolMessageType('TDError', (_message.Message,), {
    'DESCRIPTOR' : _PRIORITY_TDERROR,
    '__module__' : 'reverb.cc.patterns_pb2'
    # @@protoc_insertion_point(class_scope:deepmind.reverb.Priority.TDError)
    })
  ,
  'DESCRIPTOR' : _PRIORITY,
  '__module__' : 'reverb.cc.patterns_pb2'
  # @@protoc_insertion_point(class_scope:deepmind.reverb.Priority)
  })
_sym_db.RegisterMessage(Priority)
_sym_db.RegisterMessage(Priority.ConstantPriorityFn)
_sym_db.RegisterMessage(Priority.TDError)

StructuredWriterConfig = _reflection.GeneratedProtocolMessageType('StructuredWriterConfig', (_message.Message,), {
  'DESCRIPTOR' : _STRUCTUREDWRITERCONFIG,
  '__module__' : 'reverb.cc.patterns_pb2'
  # @@protoc_insertion_point(class_scope:deepmind.reverb.StructuredWriterConfig)
  })
_sym_db.RegisterMessage(StructuredWriterConfig)


# @@protoc_insertion_point(module_scope)
