
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: //:liga-mlflow

from setuptools import setup

setup(**{
    'install_requires': (
        'liga==0.2.0.dev12',
        'mlflow==1.26.1',
    ),
    'name': 'liga-mlflow',
    'namespace_packages': (
    ),
    'package_data': {
    },
    'packages': (
        'liga.mlflow',
    ),
    'python_requires': '<3.10,>=3.8',
    'version': '0.2.0.dev12',
})
