
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-27T19:15:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "dabb20cc18ce08dc1171cdf4489b5c0328a14585",
 "version": "1.13.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
