# Version file autogenerated by the build process
version = '0.10.0-beta5'
build = 1087
vcs_info = 'Git SHA1 5c61c876 committed on 2023-01-26'

if __name__ == '__main__':
    print('KSCONF_VERSION="0.10.0-beta5"\nKSCONF_BUILD="1087"\nKSCONF_VCS_INFO="Git SHA1 5c61c876 committed on 2023-01-26"')
