
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-26T19:40:03+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "f550cc8a38217605157191162e6a7ae0f00f5de7",
 "version": "0.0.2rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
