from distutils.core import setup
setup(
  name = 'MAHAMAHA-algorithm',
  packages = ['Code'],
  version = '0.1',
  license='MIT',
  description = 'there are no word to say',
  author = 'LJZ',
  author_email = '1572524747@qq.com',
  url = 'https://gitee.com/liujinzheng/algorithm.git',
  download_url = 'https://gitee.com/liujinzheng/algorithm/repository/archive/master.zip',
  keywords = [],
  install_requires=[
    'billiard == 4.1.0',
    'Fiona == 1.8.21',
    'GDAL == 3.4.2',
    'matplotlib == 3.4.2',
    'numpy == 1.20.2',
    'opencv_python == 4.5.5.62',
    'osgeo == 0.0.1',
    'pandas == 1.2.4',
    'Pillow == 9.4.0',
    'pyproj == 3.0.1',
    'pyshp == 2.3.1',
    'PyWavelets == 1.3.0',
    'Shapely == 2.0.0',
    'utils == 1.0.1',
      ],
  classifiers=[
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.7',
  ],
)
